export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST"
};

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'




export const USER_COMMENT_REQUEST = 'USER_COMMENT_REQUEST'
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS'
export const USER_COMMENT_FAIL = 'USER_COMMENT_FAIL'
export const USER_COMMENT_RESET = 'USER_COMMENT_RESET'

export const USER_QUESTION_REQUEST = 'USER_QUESTION_REQUEST'
export const USER_QUESTION_SUCCESS = 'USER_QUESTION_SUCCESS'
export const USER_QUESTION_FAIL = 'USER_QUESTION_FAIL'
export const USER_QUESTION_RESET = 'USER_QUESTION_RESET' 


export const USER_ANSWER_REQUEST = 'USER_ANSWER_REQUEST'
export const USER_ANSWER_SUCCESS = 'USER_ANSWER_SUCCESS'
export const USER_ANSWER_FAIL = 'USER_ANSWER_FAIL'
export const USER_ANSWER_RESET = 'USER_ANSWER_RESET'
